# Generated by Django 5.1.5 on 2025-02-01 13:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Default question in English.')),
                ('answer', ckeditor.fields.RichTextField(help_text='Answer with rich text formatting.')),
                ('question_hi', models.TextField(blank=True, help_text='Question in Hindi', null=True)),
                ('question_bn', models.TextField(blank=True, help_text='Question in Bengali', null=True)),
            ],
        ),
    ]
